/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SWING;

import DAO.NhanVienDAO;
import HELPER.DateHelper;
import HELPER.DialogHelper;
import MODEL.NhanVien;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DuongNVPH
 */
public class QuanLyNhanVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVienPanel
     */
    public QuanLyNhanVienPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        rdoNhanVien = new javax.swing.JRadioButton();
        rdoTruongPhong = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        JdcNgayNhanViec = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        JdcNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnKhoa = new javax.swing.JButton();
        btnMoKhoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Mật khẩu", "Vai trò", "Họ tên", "Ngày sinh", "Ngày nhận việc", "Địa chỉ", "Số điện thoại", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1340, 270));
        add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 200, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã nhân viên :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));
        add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 200, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mật khẩu :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        buttonGroup1.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoNhanVien.setText("Nhân viên");
        add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        buttonGroup1.add(rdoTruongPhong);
        rdoTruongPhong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoTruongPhong.setText("Trưởng phòng");
        add(rdoTruongPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Vai Trò :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Họ tên :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));
        add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 180, 40));
        add(JdcNgayNhanViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Ngày sinh :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));
        add(JdcNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 180, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Ngày nhận việc :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Địa chỉ :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Điện thoại :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Ghi Chú :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, -1));
        add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 210, 40));
        add(txtDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 210, 40));

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 210, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setBackground(new java.awt.Color(204, 204, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 113));

        btnKhoa.setBackground(new java.awt.Color(204, 204, 255));
        btnKhoa.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnKhoa.setText("KHÓA");
        jPanel1.add(btnKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 120, 110));

        btnMoKhoa.setBackground(new java.awt.Color(204, 204, 255));
        btnMoKhoa.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnMoKhoa.setText("MỞ KHÓA");
        jPanel1.add(btnMoKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 120));

        btnSua.setBackground(new java.awt.Color(204, 204, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 120));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 250, 230));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 440, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("TìM KIẾM :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMoi.setBackground(new java.awt.Color(204, 204, 255));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnMoi.setText("TẠO MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 250, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Xác nhận mật khẩu :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        add(txtXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        initTableNhanVien();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() ==2) {
            edit();
        }
        
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdcNgayNhanViec;
    private com.toedter.calendar.JDateChooser JdcNgaySinh;
    private javax.swing.JButton btnKhoa;
    private javax.swing.JButton btnMoKhoa;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoTruongPhong;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
    NhanVienDAO dao = new NhanVienDAO();
    int row =-1 ;
    void init(){
        initTableNhanVien();
        row = -1 ;
        updateStatus();
    }
    void initTableNhanVien(){
        DefaultTableModel dtm = (DefaultTableModel) tblNhanVien.getModel();
        dtm.setRowCount(0);
        String timkiem = txtTimKiem.getText();
        ArrayList<NhanVien> list = dao.selectByKeyWord(timkiem);
        try {
            for (NhanVien nhanVien : list) {
            Object[] data = {nhanVien.getMaNhanVien(),
                nhanVien.getMatKhau(),
                nhanVien.isVaiTro()?"Trưởng phòng":"Nhân viên",
                nhanVien.getHoTen(),
                DateHelper.toString(nhanVien.getNgaySinh()),
                DateHelper.toString(nhanVien.getNgayNhanVien()),
                nhanVien.getDiaChi()
                ,nhanVien.getSoDienThoai(),
                nhanVien.getGhiChu()};
            dtm.addRow(data);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    NhanVien getForm(){
        NhanVien nv = new NhanVien();
        if (txtMaNhanVien.getText().equals("")) {
            return null;
        }
        if (txtMatKhau.getText().equals("")) {
            return null;
        }
        if (txtXacNhanMatKhau.getText().equals("")) {
            return null;
        }
        if (txtHoTen.getText().equals("")) {
            return null;
        }
        if (JdcNgaySinh.getDate().equals("")) {
            return null;
        }
        if (JdcNgayNhanViec.getDate().equals("")) {
            return null;
        }
        if (txtDiaChi.getText().equals("")) {
            return null;
        }
        if (txtDienThoai.getText().equals("")) {
            return null;
        }
        nv.setMaNhanVien(txtMaNhanVien.getText());
        if (txtMatKhau.getText().equals(txtXacNhanMatKhau.getText())) {
            nv.setMatKhau(new String(txtMatKhau.getPassword()));
        }else{
            DialogHelper.alert(this, "Mật khẩu không khớp !");
            return null ;
        }
        nv.setVaiTro(!rdoTruongPhong.isSelected());
        nv.setHoTen(txtHoTen.getText());
        nv.setNgaySinh(JdcNgaySinh.getDate());
        nv.setNgayNhanVien(JdcNgayNhanViec.getDate());
        nv.setDiaChi(txtDiaChi.getText());
        nv.setSoDienThoai(txtDienThoai.getText());
        nv.setGhiChu(txtGhiChu.getText());
        return nv;
    }
    void setForm(NhanVien nv){
        txtMaNhanVien.setText(nv.getMaNhanVien());
        txtMatKhau.setText(nv.getMatKhau());
        txtXacNhanMatKhau.setText(nv.getMatKhau());
        rdoNhanVien.setSelected(!nv.isVaiTro());
        rdoTruongPhong.setSelected(nv.isVaiTro());
        txtHoTen.setText(nv.getHoTen());
        JdcNgaySinh.setDate(nv.getNgaySinh());
        JdcNgayNhanViec.setDate(nv.getNgayNhanVien());
        txtDiaChi.setText(nv.getDiaChi());
        txtDienThoai.setText(nv.getSoDienThoai());
        txtGhiChu.setText(nv.getGhiChu());
    }
    void updateStatus(){
        boolean edit = this.row >= 0 ;
        boolean first = this.row == 0 ;
        boolean last = this.row == tblNhanVien.getRowCount() - 1 ;
        
        txtMaNhanVien.setEnabled(!edit);
        btnThem.setEnabled(!edit);
        btnKhoa.setEnabled(edit);
        btnMoKhoa.setEnabled(edit);
        btnSua.setEnabled(edit);
    }
    
    void edit(){
        DefaultTableModel dtm = (DefaultTableModel) tblNhanVien.getModel();
        row = tblNhanVien.getSelectedRow();
        if (row == -1) {
            return ;
        }
        txtMaNhanVien.setText(dtm.getValueAt(row, 0).toString());
        txtHoTen.setText(dtm.getValueAt(row, 3).toString());
        txtMatKhau.setText(dtm.getValueAt(row, 1).toString());
        txtXacNhanMatKhau.setText(dtm.getValueAt(row, 1).toString());
        JdcNgaySinh.setDate(DateHelper.toDate(dtm.getValueAt(row, 4).toString()));
        JdcNgayNhanViec.setDate(DateHelper.toDate(dtm.getValueAt(row, 5).toString()));
        txtDiaChi.setText(dtm.getValueAt(row, 6).toString());
        txtDienThoai.setText(dtm.getValueAt(row, 7).toString());
        txtGhiChu.setText(dtm.getValueAt(row, 8).toString());
        if (dtm.getValueAt(row, 2).toString().equals("Nhân viên")) {
            rdoNhanVien.setSelected(true);
        }else{
            rdoTruongPhong.setSelected(true);
        }
        updateStatus();
    }
    void clear(){
        NhanVien nv = new NhanVien();
        setForm(nv);
        row =-1 ;
        updateStatus();
    }
    void insert(){
        NhanVien nv = this.getForm();
        if (nv == null) {
            return ;
        }
        try {
            dao.insert(nv);
            initTableNhanVien();
            clear();
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    void update(){
        NhanVien nv = this.getForm();
        if (nv == null ) {
            return ;
        }
        try {
            dao.update(nv);
            initTableNhanVien();
            clear();
            DialogHelper.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
